name: test
on:
 push:


jobs:
 if-windows-else:
    runs-on: ubuntu-latest

    steps:

      - name: condition 1
        if: runner.os == 'Windows'
        run: echo "The operating system on the runner is ${{ RUNNER.OS }}

      - name: condition 2
        if: runner.os != 'Windows'
        run: echo "The operaning system on the runner is not Windows, it's $RUNNER_OS."
