#-------------------
# Ara
#-------------------
name: mysecondtest

on:
  push:
    branches: 
      - master
jobs:
  mytest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello
          run: echo "Hello World"
