#My Second test

name: test2

on:
  push:
  
jobs:
  test-job:
   runs-on: ubuntu-latest
   steps:
   - uses:  actions/checkout@v3
     with:
      ref: ${{ github.event.pull_request.head.sha }}
   
   - name: test2  
     run: echo "Test2"
