# Tumanyan Ara test1

name: mytest1

on:
  push:
    branches:
      - main
      
jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Messege
        run: echo "Hello, world from test!"


  my_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Messege
        run: echo "Hello, world from deploy!"
